name: master-thesis_cuda113
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision  # 11.1. to run MNIST as GPU test
  - cudatoolkit=11.3 # newest version 11.3 might not work
  - pandas
  - scikit-learn
  - seaborn
  - transformers
  - tensorboard
  - requests
  - sparqlwrapper
  - ipython
  - tqdm
  - pip
  - pip:
    - pykeen
    - torchmetrics
    - pylustrator  # 17.12.21
    - tensorboard  # 4.1.21

