name: master-thesis
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - nvidia::cudatoolkit=11.3
  - python=3.9
  - pytorch::pytorch
  - transformers=4.15
  - pandas
  - seaborn
  - tensorboard
  - ipython
  - tqdm
  - enlighten  # 21.2. for adding progress to logging file
  - ignite=0.4.8  # 20.1.22: necessary for running Keidar code
  - pip
  - pip:
    - pykeen
    - torchmetrics
    - tensorboard  # 4.1.21


