name: master-thesis_16_11_21
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - scikit-learn
  - seaborn
  - pytorch
  - cpuonly
  - transformers
  - tensorboard
  - requests
  - sparqlwrapper
  - ipython
  - tqdm
  - pip
  - pip:
    - pykeen
    - torchmetrics

