KvsAll:
  label_smoothing: 0.08472616542130706
conve:
  entity_embedder:
    dropout: 0.48281603772193193
    regularize_weight: 1.0271379860039192e-16
  feature_map_dropout: 0.26491457130759954
  projection_dropout: 0.278989402577281
  relation_embedder:
    dropout: -0.2679508440196514
    regularize_weight: 0.005247464644229938
  round_dim: true
dataset:
  name: codex-m
  num_entities: 17050
  num_relations: 51
eval:
  batch_size: 256
  metrics_per:
    relation_type: true
import:
- reciprocal_relations_model
- conve
lookup_embedder:
  dim: 512
  initialize: xavier_uniform_
  initialize_args:
    normal_:
      mean: 0.0
      std: 0.0036635867498266716
    uniform_:
      a: -0.275826295682881
    xavier_normal_:
      gain: 1.0
    xavier_uniform_:
      gain: 1.0
  regularize_args:
    p: 3
    weighted: true
model: reciprocal_relations_model
negative_sampling:
  implementation: batch
reciprocal_relations_model:
  base_model:
    entity_embedder:
      dim: 512
    relation_embedder:
      dim: 512
train:
  auto_correct: true
  batch_size: 1024
  loss_arg: .nan
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    factor: 0.95
    mode: max
    patience: 6
    threshold: 0.0001
  max_epochs: 400
  optimizer_args:
    lr: 0.03779768742356302
valid:
  early_stopping:
    min_threshold:
      epochs: 50
      metric_value: 0.05

